CREATE TABLE COMPANIES (
	ID SERIAL NOT NULL,
	DATA_ABERTURA DATE NOT NULL,
	NOME_FANTASIA VARCHAR(255) NOT NULL , 
	RAZAO_SOCIAL VARCHAR(255),
	CNPJ VARCHAR(14) NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
	UPDATE_DATE TIMESTAMP,
	DELETE_DATE TIMESTAMP,
	CONTA_ID INT, 
	CONSTRAINT COMPANIES_PK PRIMARY KEY (ID)
);

ALTER TABLE COMPANIES 
	ADD CONSTRAINT FK_CONTA_IN_COMPANIES FOREIGN KEY (CONTA_ID) REFERENCES ACCOUNTS;