CREATE TABLE REVINFO 
  ( 
     REV BIGINT NOT NULL, 
     REVTSTMP NUMERIC(19, 0), 
     REMOTE_ADDRESS VARCHAR(255), 
     USERNAME VARCHAR(255), 
     PRIMARY KEY (REV) 
); 
  
CREATE TABLE ACCOUNTS_AUD (
 	ID SERIAL NOT NULL, 
    REV BIGSERIAL NOT NULL, 
    REVTYPE SMALLSERIAL, 
    AGENCIA VARCHAR(20), 
	SALDO NUMERIC(19,2),
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
	UPDATE_DATE TIMESTAMP,
	DELETE_DATE TIMESTAMP,
    PRIMARY KEY (ID, REV) 
);
 

CREATE TABLE COMPANIES_AUD (
  	 ID SERIAL NOT NULL, 
     REV BIGSERIAL NOT NULL, 
     REVTYPE SMALLSERIAL, 
     NOME_FANTASIA VARCHAR(255), 
	 RAZAO_SOCIAL VARCHAR(255),
	 CPNJ VARCHAR(14),
	 SALDO_CORRENTE NUMERIC(19,2),
	 SALDO_POUPACA NUMERIC(19,2),
	 CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
	 UPDATE_DATE TIMESTAMP,
	 DELETE_DATE TIMESTAMP,
     PRIMARY KEY (ID, REV) 
);

  
CREATE TABLE EMPLOYEES_AUD (
  	 ID SERIAL NOT NULL, 
     REV BIGSERIAL NOT NULL, 
     REVTYPE SMALLSERIAL, 
     NOME_FANTASIA VARCHAR(255), 
	 RAZAO_SOCIAL VARCHAR(255),
	 CPNJ VARCHAR(14),
	 SALDO_CORRENTE NUMERIC(19,2),
	 SALDO_POUPACA NUMERIC(19,2),
	 CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
	 UPDATE_DATE TIMESTAMP,
	 DELETE_DATE TIMESTAMP,
     PRIMARY KEY (ID, REV) 
);

ALTER TABLE COMPANIES_AUD 
  ADD CONSTRAINT FK_COMPANIES_AUD_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO; 
  
ALTER TABLE EMPLOYEES_AUD 
  ADD CONSTRAINT FK_EMPLOYEES_AUD_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO;
  
ALTER TABLE ACCOUNTS_AUD 
  ADD CONSTRAINT FK_ACCOUNTS_AUD_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO;  