CREATE TABLE EMPLOYEES (
	ID SERIAL NOT NULL,
	COMPANY_ID INT, 
	NOME_CURTO VARCHAR(20), 
	NOME_COMPLETO VARCHAR(255), 
	CPF VARCHAR(11), 
	DATA_NASCIMENTO DATE, 
	SALARIO NUMERIC(19,2), 
	DATA_ADMISSAO DATE, 
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
	UPDATE_DATE TIMESTAMP,
	DELETE_DATE TIMESTAMP,
	CONTA_ID INT, 
	CONSTRAINT EMPLOYESS_PK PRIMARY KEY (ID)
);

ALTER TABLE EMPLOYEES 
	ADD CONSTRAINT FK_COMPANIES_IN_EMPLOYEES FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES;
	
	
ALTER TABLE EMPLOYEES 
	ADD CONSTRAINT FK_CONTA_IN_EMPLOYEES FOREIGN KEY (CONTA_ID) REFERENCES ACCOUNTS;